apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: my-app-ns
spec:
  limits:
    - default:
        cpu: 400m
        memory: 1000Mi
      defaultRequest:
        cpu: 400m
        memory: 1000Mi
      max:
        cpu: 400m
        memory: 1000Mi
      min:
        cpu: 400m
        memory: 1000Mi
      type: Container
